# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='money_value',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='at_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='emission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
