# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='user',
        ),
        migrations.DeleteModel(
            name='PayCheck',
        ),
    ]
