# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20180502_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.IntegerField(unique=True)),
                ('beneficiary', models.CharField(max_length=100)),
                ('money_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('concept', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank', to='dashboard.Bank')),
                ('pay_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_date', to='dashboard.PaymentDate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
