# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-04 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180503_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='pay_date',
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='beneficiary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='check_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='concept',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
