# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_paycheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='money_value',
        ),
    ]
