# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180506_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='at_date',
            field=models.DateField(blank=True, default='3000-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='post_date',
            field=models.DateField(blank=True, default='3000-12-31', null=True),
        ),
    ]
