# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180506_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='emission_date',
            field=models.DateField(),
        ),
    ]
