# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180506_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
