# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_paycheck_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
