# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180513_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='completado',
        ),
    ]
