# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_remove_paycheck_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(default=' ', max_length=5000)),
                ('leido', models.CharField(default='no', max_length=100)),
                ('prioridad', models.IntegerField(default=0)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('remitente', models.IntegerField(default=0)),
                ('pedido_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
