# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='estado',
            field=models.IntegerField(default=10),
        ),
    ]
